export enum ErrorCodes {
  DOMAIN_ERROR = 'DOMAIN_ERROR',
  DOMAIN_ENTITY_VALIDATION_ERROR = 'ENTITY_VALIDATION_ERROR',
  APPLICATION_ERROR = 'APPLICATION_ERROR',
  INFRASTRUCTURE_ERROR = 'INFRASTRUCTURE_ERROR',
  BASE_ERROR = 'BASE_ERROR',
};
